name: playdough
favicon: null
layout_spectrum: 0.9919085092842579
typography_spectrum: 0.03137905313633382
title: playing with dough
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
