name: playdough
favicon: null
layout_spectrum: 0.06194
typography_spectrum: 0.11482
title: playing with dough
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffff01'
    - '#ffb200'
    - '#404f86'
    - '#43bdec'
  brandStrength: 0
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
